/*
 * File: app/model/PersonBaseInfoForShow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HRMS.model.PersonBaseInfoForShow', {
	extend : 'Ext.data.Model',

	fields : [ {
		name : 'empNo'
	}, {
		name : 'name'
	}, {
		name : 'sex'
	}, {
		name : 'ethnic'
	}, {
		name : 'dob',
		type : 'date',
		dateFormat : 'Y/m/d'
	}, {
		name : 'idCard'
	}, {
		name : 'hometown'
	}, {
		name : 'birthPlace'
	}, {
		name : 'department'
	}, {
		name : 'sub_unit'
	}, {
		name : 'dateOfStartWork',
		type : 'date',
		dateFormat : 'Y/m'
	}, {
		name : 'dateOfEntry',
		type : 'date',
		dateFormat : 'Y/m/d'
	}, {
		name : 'jobType'
	}, {
		name : 'teacher_type'
	}, {
		name : 'nationality'
	}, {
		name : 'retirementDate',
		type : 'date',
		dateFormat : 'Y/m/d'
	}, {
		name : 'updateTime',
		type : 'date',
		dateFormat : 'Y/m/d'
	}, {
		name : 'workState'
	}, {
		name : 'remark'
	}, {
		name : 'manage_post'
	}, {
		name : 'tech_post'
	}, {
		name : 'quotaType'
	}, {
		name : 'etc1'
	}, {
		name : 'etc2'
	} ]
});