/*
 * File: app/view/addPersonBaseInfoWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HRMS.view.addPersonBaseInfoWindow', {
    extend: 'Ext.window.Window',

    height: 479,
    padding: 10,
    width: 614,
    layout: {
        align: 'stretch',
        pack: 'center',
        type: 'hbox'
    },
    title: '添加人员',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 450,
                    layout: {
                        type: 'hbox'
                    },
                    bodyPadding: 10,
                    manageHeight: false,
                    title: '',
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 353,
                            maxWidth: 250,
                            padding: 10,
                            width: 250,
                            title: '基本信息',
                            toggleOnTitleClick: false,
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 225,
                                    fieldLabel: '姓名',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'name'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 225,
                                    fieldLabel: '工号',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'workNumber'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 225,
                                    fieldLabel: '年龄',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'age'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 225,
                                    fieldLabel: '性别',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'sex'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 225,
                                    fieldLabel: '民族',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'ethnic'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 225,
                                    fieldLabel: '身份证',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'idNumber'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 225,
                                    fieldLabel: '部门',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'department'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 225,
                                    fieldLabel: '职务',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'post'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 225,
                                    fieldLabel: '岗位类型',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'jobType'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 225,
                                    fieldLabel: '级别',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'level'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 225,
                                    fieldLabel: '职称',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'personalTitle'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            margin: '0 0 0 20',
                            maxWidth: 250,
                            padding: 10,
                            title: '照片',
                            toggleOnTitleClick: false,
                            items: [
                                {
                                    xtype: 'panel',
                                    border: 1,
                                    height: 250,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    bodyBorder: true,
                                    title: ''
                                },
                                {
                                    xtype: 'filefield',
                                    margin: '10 0 0 0',
                                    width: 225,
                                    fieldLabel: '上传照片',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'personalTitle'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    width: 150,
                                    text: '确定'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});