/*
 * File: app/view/PersonDetailInfoWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HRMS.view.PersonDetailInfoWindow', {
    extend: 'Ext.window.Window',

    border: '2 solid #157FCC',
    height: 600,
    padding: 10,
    width: 1100,
    overflowY: 'auto',
    bodyBorder: true,
    title: '个人详细信息',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '内容',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: '详细'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: '普通'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: '简略'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            text: '导出',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Word文件'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'PDF文件'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            text: '打印'
                        },
                        {
                            xtype: 'splitbutton',
                            text: '内容定位',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    height: 2000,
                    html: '<iframe scrolling="auto" frameborder="0" width="100%" height="100%" src="cv.html"></iframe>"></iframe>',
                    title: ''
                }
            ]
        });

        me.callParent(arguments);
    }

});